spring.application.name=api

pharmelys.bdpm.base-url = https://base-donnees-publique.medicaments.gouv.fr/index.php/download/file/
pharmelys.bdpm.specialites-file = CIS_bdpm.txt
pharmelys.bdpm.compositions-file = CIS_COMPO_bdpm.txt
pharmelys.bdpm.groupes-generiques-file = CIS_GENER_bdpm.txt
pharmelys.bdpm.ruptures-file = CIS_CIP_Dispo_Spec.txt
pharmelys.bdpm.import-on-startup = true

spring.config.import=optional:classpath:env.properties